CREATE TABLE logs (
                      id Bigint generated by default as identity primary key ,
                      action_time TIMESTAMP DEFAULT NOW(),
                      action_type VARCHAR(50),
                      description TEXT
);


-- Функция логирования
CREATE OR REPLACE FUNCTION log_product_insert()
    RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO logs (action_type, description)
    VALUES (
               'INSERT',
               'Добавлен новый товар:'
           );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Триггер для таблицы product_info
CREATE TRIGGER log_product_insert_trigger
    AFTER INSERT ON product_info
    FOR EACH ROW EXECUTE FUNCTION log_product_insert();


